version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always
    environment:
      - NODE_ENV=production
